#!/bin/bash

echo "📦 Data-TestID Scanner - Instalação"
echo ""
echo "⚠️  Chrome desabilitou CRXs externos desde jan/2025"
echo "✅ Use 'Load unpacked' com a pasta dist/"
echo ""
echo "📂 Caminho da pasta dist:"
echo "   $(realpath dist)"
echo ""
echo "🔧 Passos:"
echo "   1. Abra chrome://extensions/"
echo "   2. Ative 'Developer mode' (canto superior direito)"
echo "   3. Clique em 'Load unpacked'"
echo "   4. Selecione a pasta: $(realpath dist)"
echo ""
echo "📌 Ou use o ZIP:"
echo "   1. Extraia data-test-id-scanner.zip"
echo "   2. Carregue a pasta extraída em 'Load unpacked'"